apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-server.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ include "config-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "config-server.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "config-server.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "config-server.fullname" . }}-sa
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "config-server.fullname" . }}-akv
      containers:
        - name: config-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.azureKeyVault.secrets.username }}
                  key: {{ .Values.global.azureKeyVault.secrets.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.azureKeyVault.secrets.password }}
                  key: {{ .Values.global.azureKeyVault.secrets.password }}
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
