# Image settings
image:
  repository: abbdemoazdevacr.azurecr.io/demo-myapp
  tag: "latest"
  pullPolicy: Always

# If your AKS has ACR Pull (recommended), leave this empty.
# If you need a docker-registry secret, set: imagePullSecrets: [{ name: "acr-pull" }]
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

replicaCount: 2

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

# HTTP readiness/liveness probes
probes:
  path: /
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: demo-myapp.example.com
      paths:
        - path: /
          pathType: Prefix
  #tls: []
  # - secretName: demo-myapp-tls
  #   hosts:
  #     - demo-myapp.example.com

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70