replicaCount: 2

image:
  repository: "{{ .Values.global.acr }}/{{ .Values.global.imageNamespace }}/chat-agent"
  tag: "{{ .Values.global.imageTag }}"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

containerPort: 8080