workloadIdentity:
  clientId: "2083f38f-820b-4293-b728-e92e90fc0024"

mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.131.0

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
  processors:
    batch: {}
  exporters:
    azuremonitor:
      connection_string: "InstrumentationKey=20ff652e-3ce4-4811-95cb-50bba11f8a8b;IngestionEndpoint=https://centralus.ingestion.monitor.azure.com/"
      endpoint: "https://dc.services.visualstudio.com/v2/track"
    #otlp/azure:
    #  endpoint: "https://otlp.monitor.azure.com:4317"
    #  authentication:
    #    aad:
    #      managed_identity:
    #        client_id: "{{ .Values.workloadIdentity.clientId }}"
    #  sending_queue:
    #    enabled: true
    #    num_consumers: 2
    #    queue_size: 2000
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [azuremonitor]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [azuremonitor]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [azuremonitor]